"""empty message

Revision ID: 620f827577c4
Revises: 7aeac31ead87
Create Date: 2021-01-24 22:31:40.118538

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '620f827577c4'
down_revision = '7aeac31ead87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('followed_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], name='followers_ibfk_2'),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], name='followers_ibfk_1'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
